sonar.organization=badoriie
sonar.projectKey=badoriie_revolut-trader

sonar.sources=src/,cli/
sonar.tests=tests/

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc,revt-data/**,.venv/**
sonar.test.exclusions=tests/**

sonar.qualitygate.wait=true
